# Generated by Django 4.2.6 on 2023-11-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creating_blog',
            name='slug',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
