# Generated by Django 4.2.6 on 2023-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0002_alter_creating_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creating_blog',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
        ),
    ]
