# Generated by Django 4.2.6 on 2023-11-05 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creating_blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=300, verbose_name='Blog Title')),
                ('blog_content', models.TextField(verbose_name='Write Your Blog ')),
                ('blog_image', models.ImageField(upload_to='image_blog')),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('published_data', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('blogger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
