# Generated by Django 4.2.6 on 2023-10-28 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_remove_make_quiz_quiz_titile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_quiz',
            name='quiz_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='make_quiz',
            name='quiz_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='quiz.quiz_category'),
        ),
    ]
