# Generated by Django 4.2.6 on 2023-10-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_alter_make_quiz_quiz_maker_alter_make_quiz_quiz_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demoquiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('option_1', models.CharField(blank=True, max_length=250, null=True)),
                ('option_2', models.CharField(blank=True, max_length=250, null=True)),
                ('option_3', models.CharField(blank=True, max_length=250, null=True)),
                ('option_4', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, choices=[('option-1', 'option-1'), ('option-2', 'option-2'), ('option-2', 'option-2'), ('option-2', 'option-2')], default='Select answer', max_length=250, null=True)),
                ('quiz_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizer', to=settings.AUTH_USER_MODEL)),
                ('quiz_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_type', to='quiz.quiz_category')),
            ],
        ),
    ]
