# Generated by Django 4.2.6 on 2023-10-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_confirmation',
            old_name='user',
            new_name='user_acc',
        ),
    ]
