# Generated by Django 4.2.6 on 2023-10-28 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='make_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_titile', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('option_1', models.CharField(blank=True, max_length=250, null=True)),
                ('option_2', models.CharField(blank=True, max_length=250, null=True)),
                ('option_3', models.CharField(blank=True, max_length=250, null=True)),
                ('option_4', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.CharField(blank=True, max_length=250, null=True)),
                ('quiz_maker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_maker', to=settings.AUTH_USER_MODEL)),
                ('quiz_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='quiz.quiz_category')),
            ],
        ),
    ]
