# Generated by Django 4.2.6 on 2023-10-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_demoquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_category',
            name='under_whom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demoquiz',
            name='answer',
            field=models.CharField(blank=True, choices=[('option-1', 'option-1'), ('option-2', 'option-2'), ('option-3', 'option-3'), ('option-4', 'option-4')], default='Select answer', max_length=250, null=True),
        ),
    ]
