# Generated by Django 4.2.6 on 2023-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_student_score_ques_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_score',
            name='total_quiz_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
