# Generated by Django 4.2.6 on 2023-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_student_score_ques_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_category',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
