# Generated by Django 4.2.6 on 2023-11-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quiz_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_score',
            name='ques_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_category'),
        ),
    ]
